config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  root "restaurants#index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @new_restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(post_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :tel, :address, :url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpartaTabelog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- ★★★★下記の#を後ほど正しいURLに変更 -->
        <a class="navbar-brand" href="/">Sparta Tabelog</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <!-- ★★★★下記の#を後ほど正しいURLに変更 -->
          <li><a href="/restaurants/new">投稿する</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/restaurants/edit.html.erb
<div class="col-md-12">
  <h1>食べログ記事編集</h1>
  <%= form_for @restaurant do |f| %>
    <div class="form-group">
      <%= f.label "お店の名前" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "電話番号" %>
      <%= f.text_field :tel, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "住所" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "お店のURL" %>
      <%= f.text_field :url, class: "form-control" %>
    </div>

    <%= f.submit '更新する', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="col-md-8">
  <% @restaurants.each do |restaurant| %>
    <div class="article">
      <h2>名前：<%= restaurant.name %></h2>
      <p>電話番号：<%= restaurant.tel %></p>
      <p>作成日：<%= restaurant.created_at %></p>
      <p><%= link_to "詳細", restaurant, class: "btn btn-default" %></p>
    </div>
  <% end %>
</div>

<div class="col-md-4">
  <div class="thumbnail">
    <%= image_tag User.first.image_url, alt: "著者イメージ" %>
    <div class="caption">
      <h3>著者名：<%= User.first.name %></h3>
      <p>詳細：<%= User.first.description %></p>
      <p>TEL：<%= User.first.tel %></p>
      <p>EMAIL：<%= User.first.email %></p>

    </div>
  </div>
  <div class="list-group">
    <% @restaurants.each_with_index do |restaurant, index| %>
    <% if index >= 5
         break
       end
    %>
    <%= link_to restaurant.name, restaurant, class: "list-group-item" %>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="col-md-12">
  <h1>食べログ記事投稿</h1>
  <%= form_for @restaurant do |f| %>
    <div class="form-group">
      <%= f.label "お店の名前" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "電話番号" %>
      <%= f.text_field :tel, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "住所" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "お店のURL" %>
      <%= f.text_field :url, class: "form-control" %>
    </div>

    <%= f.submit '投稿する', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="col-md-12">
  <h1><%= @restaurant.name %></h1>
  <p>電話番号: <%= @restaurant.tel %></p>
  <p>住所: <%= @restaurant.address %></p>
  <p>このお店のURL: <%= @restaurant.url %></p>
  <p>投稿日:<%= @restaurant.created_at %></p>
  <hr>
  <%= link_to "編集", edit_restaurant_path(@restaurant), class: "btn btn-default" %>
  <%= link_to "削除", restaurant_path(@restaurant), class: "btn btn-default", method: :delete %>
</div>